"""Initial schema

Revision ID: c5972da5d55d
Revises: 6de9103a103d
Create Date: 2025-10-12 08:40:01.250131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5972da5d55d'
down_revision: Union[str, None] = '6de9103a103d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('major', sa.String(length=100), nullable=True))
    op.drop_column('students', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('students', 'major')
    # ### end Alembic commands ###
