"""add ai_session_id to attendance_sessions

Revision ID: bb1a342bae35
Revises: cdca9cebf828
Create Date: 2025-10-24 21:07:57.391895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1a342bae35'
down_revision: Union[str, None] = 'cdca9cebf828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_sessions', sa.Column('ai_session_id', sa.String(length=255), nullable=True, comment='AI Service session ID for face recognition'))
    op.create_unique_constraint(None, 'attendance_sessions', ['ai_session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance_sessions', type_='unique')
    op.drop_column('attendance_sessions', 'ai_session_id')
    # ### end Alembic commands ###
