"""Class schema modify

Revision ID: 61c9b47de1e9
Revises: c5972da5d55d
Create Date: 2025-10-14 20:04:00.685586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61c9b47de1e9'
down_revision: Union[str, None] = 'c5972da5d55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_schedules', sa.Column('schedule_data', sa.JSON(), nullable=False, comment='Weekly schedule: {day: [periods]}'))
    op.drop_index('ix_class_schedule_class_day', table_name='class_schedules')
    op.create_index('ix_class_schedule_class_id', 'class_schedules', ['class_id'], unique=False)
    op.drop_column('class_schedules', 'day_of_week')
    op.drop_column('class_schedules', 'start_time')
    op.drop_column('class_schedules', 'location')
    op.drop_column('class_schedules', 'end_time')
    op.add_column('classes', sa.Column('location', sa.String(length=255), nullable=True))
    op.alter_column('classes', 'description',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'description',
               existing_type=sa.String(length=255),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('classes', 'location')
    op.add_column('class_schedules', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('class_schedules', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('class_schedules', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('class_schedules', sa.Column('day_of_week', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.drop_index('ix_class_schedule_class_id', table_name='class_schedules')
    op.create_index('ix_class_schedule_class_day', 'class_schedules', ['class_id', 'day_of_week'], unique=False)
    op.drop_column('class_schedules', 'schedule_data')
    # ### end Alembic commands ###
