"""leave_request table modify

Revision ID: 8bb7f6bb05a2
Revises: 690a0af33322
Create Date: 2025-10-19 16:02:22.607059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bb7f6bb05a2'
down_revision: Union[str, None] = '690a0af33322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('leave_date', sa.DateTime(), nullable=False))
    op.add_column('leave_requests', sa.Column('day_of_week', sa.String(length=20), nullable=False))
    op.add_column('leave_requests', sa.Column('time_slot', sa.String(length=50), nullable=True))
    op.drop_column('leave_requests', 'leave_dates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('leave_dates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('leave_requests', 'time_slot')
    op.drop_column('leave_requests', 'day_of_week')
    op.drop_column('leave_requests', 'leave_date')
    # ### end Alembic commands ###
