"""Add file_key and is_public to files table

Revision ID: 4ece829d0428
Revises: c5972da5d55d
Create Date: 2025-10-14 15:25:01.584849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ece829d0428'
down_revision: Union[str, None] = 'c5972da5d55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_key', sa.String(length=500), nullable=False))
    op.add_column('files', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.drop_column('files', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('files', 'is_public')
    op.drop_column('files', 'file_key')
    # ### end Alembic commands ###
