"""change_student_major_to_department_id

Revision ID: 6fed2c1112a6
Revises: 69c66c99a8ee
Create Date: 2025-10-20 16:34:30.634116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fed2c1112a6'
down_revision: Union[str, None] = '69c66c99a8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_column('students', 'major')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('major', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'department_id')
    # ### end Alembic commands ###
