"""leave_request table modify

Revision ID: dda2e4b93a77
Revises: 8bb7f6bb05a2
Create Date: 2025-10-19 20:53:58.486018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda2e4b93a77'
down_revision: Union[str, None] = '8bb7f6bb05a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
