"""leave_request table modify

Revision ID: 6c8385eb9848
Revises: dda2e4b93a77
Create Date: 2025-10-19 20:59:54.714862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8385eb9848'
down_revision: Union[str, None] = 'dda2e4b93a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('leave_requests_reviewed_by_fkey', 'leave_requests', type_='foreignkey')
    op.create_foreign_key(None, 'leave_requests', 'teachers', ['reviewed_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.create_foreign_key('leave_requests_reviewed_by_fkey', 'leave_requests', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
