"""Add day_of_week, period_range, and session_index to attendance_sessions

Revision ID: cdca9cebf828
Revises: 8a3478de17f6
Create Date: 2025-10-23 21:06:38.794793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdca9cebf828'
down_revision: Union[str, None] = '8a3478de17f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_sessions', sa.Column('day_of_week', sa.Integer(), nullable=True, comment='Day of week (0=Sunday, 1=Monday, ..., 6=Saturday)'))
    op.add_column('attendance_sessions', sa.Column('period_range', sa.String(length=50), nullable=True, comment="Period range (e.g., '1-3' or '6-7')"))
    op.add_column('attendance_sessions', sa.Column('session_index', sa.Integer(), nullable=True, comment='Session index for the day (0, 1, 2, ...)'))
    op.drop_index('idx_face_embeddings_student_id', table_name='face_embeddings')
    op.drop_index('idx_face_embeddings_vector_l2', table_name='face_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_face_embeddings_vector_l2', 'face_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_face_embeddings_student_id', 'face_embeddings', ['student_id'], unique=False)
    op.drop_column('attendance_sessions', 'session_index')
    op.drop_column('attendance_sessions', 'period_range')
    op.drop_column('attendance_sessions', 'day_of_week')
    # ### end Alembic commands ###
