"""add face registration progress fields

Revision ID: 3edd3e2de680
Revises: d3b169b201ed
Create Date: 2025-10-22 11:25:27.265293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3edd3e2de680'
down_revision: Union[str, None] = 'd3b169b201ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_registration_requests', sa.Column('total_images_captured', sa.Integer(), nullable=True))
    op.add_column('face_registration_requests', sa.Column('registration_progress', sa.Float(), nullable=True))
    op.add_column('face_registration_requests', sa.Column('verification_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face_registration_requests', 'verification_data')
    op.drop_column('face_registration_requests', 'registration_progress')
    op.drop_column('face_registration_requests', 'total_images_captured')
    # ### end Alembic commands ###
