"""add_department_and_specialization_tables

Revision ID: 69c66c99a8ee
Revises: 2234b4c274f1
Create Date: 2025-10-20 10:48:21.475765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c66c99a8ee'
down_revision: Union[str, None] = '2234b4c274f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('specializations',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specializations_code'), 'specializations', ['code'], unique=False)
    op.create_index(op.f('ix_specializations_id'), 'specializations', ['id'], unique=False)
    op.add_column('teachers', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('teachers', sa.Column('specialization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teachers', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'teachers', 'specializations', ['specialization_id'], ['id'], ondelete='SET NULL')
    op.drop_column('teachers', 'department')
    op.drop_column('teachers', 'specialization')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('specialization', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'specialization_id')
    op.drop_column('teachers', 'department_id')
    op.drop_index(op.f('ix_specializations_id'), table_name='specializations')
    op.drop_index(op.f('ix_specializations_code'), table_name='specializations')
    op.drop_table('specializations')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
