"""enable_pgvector_and_update_face_embeddings

Revision ID: a4798d1b28bf
Revises: 1ebb5c08de8c
Create Date: 2025-10-21 16:01:43.142022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'a4798d1b28bf'
down_revision: Union[str, None] = '1ebb5c08de8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension first
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_embeddings', sa.Column('student_code', sa.String(length=20), nullable=True))
    
    # Populate student_code from students table
    op.execute("""
        UPDATE face_embeddings fe
        SET student_code = s.student_code
        FROM students s
        WHERE fe.student_id = s.id
    """)
    
    # Make student_code non-nullable
    op.alter_column('face_embeddings', 'student_code', nullable=False)
    
    # Convert embedding column to vector type
    op.alter_column('face_embeddings', 'embedding',
               existing_type=sa.TEXT(),
               type_=Vector(512),
               existing_nullable=False,
               postgresql_using='embedding::vector')
    
    # Create indexes
    op.create_index(op.f('ix_face_embeddings_student_code'), 'face_embeddings', ['student_code'], unique=False)
    op.create_index(op.f('ix_face_embeddings_student_id'), 'face_embeddings', ['student_id'], unique=False)
    
    # Create vector similarity index
    op.execute("""
        CREATE INDEX idx_face_embeddings_vector_cosine 
        ON face_embeddings 
        USING ivfflat (embedding vector_cosine_ops) 
        WITH (lists = 100)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.execute('DROP INDEX IF EXISTS idx_face_embeddings_vector_cosine')
    op.drop_index(op.f('ix_face_embeddings_student_id'), table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_student_code'), table_name='face_embeddings')
    
    # Convert embedding back to text
    op.alter_column('face_embeddings', 'embedding',
               existing_type=Vector(512),
               type_=sa.TEXT(),
               existing_nullable=False,
               postgresql_using='embedding::text')
    
    # Drop student_code column
    op.drop_column('face_embeddings', 'student_code')
    # ### end Alembic commands ###
