"""add_tenant_secrets

Revision ID: 4bb1de1f413c
Revises: a1a097c22a22
Create Date: 2026-05-28 11:33:06.122667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb1de1f413c'
down_revision: Union[str, None] = 'a1a097c22a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_secrets',
    sa.Column('key_name', sa.String(length=100), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_name', name='uq_tenant_secrets_key_name')
    )
    op.create_index(op.f('ix_tenant_secrets_id'), 'tenant_secrets', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_secrets_key_name'), 'tenant_secrets', ['key_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_secrets_key_name'), table_name='tenant_secrets')
    op.drop_index(op.f('ix_tenant_secrets_id'), table_name='tenant_secrets')
    op.drop_table('tenant_secrets')
    # ### end Alembic commands ###
