"""course's code change to not  unique

Revision ID: a0f835c4973a
Revises: ac21d6761d3c
Create Date: 2026-04-29 20:35:51.866758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f835c4973a'
down_revision: Union[str, None] = 'ac21d6761d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courses_code', table_name='courses')
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.create_index('ix_courses_code', 'courses', ['code'], unique=False)
    # ### end Alembic commands ###
