"""add teacherid to course model

Revision ID: ac21d6761d3c
Revises: 6720ff4a6b78
Create Date: 2026-04-29 15:51:59.316174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac21d6761d3c'
down_revision: Union[str, None] = '6720ff4a6b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_courses_teacher_id'), 'courses', ['teacher_id'], unique=False)
    op.create_foreign_key(None, 'courses', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_teacher_id'), table_name='courses')
    op.drop_column('courses', 'teacher_id')
    # ### end Alembic commands ###
