"""Add course_id to classes

Revision ID: c69f8f7f5503
Revises: 2026_04_18_1500
Create Date: 2026-04-26 11:24:07.808046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69f8f7f5503'
down_revision: Union[str, None] = '2026_04_18_1500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('course_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'classes', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.alter_column('document_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_document_chunks_chunk_text_trgm', table_name='document_chunks', postgresql_ops={'chunk_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_spoof_detections_id'), 'spoof_detections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spoof_detections_id'), table_name='spoof_detections')
    op.create_index('idx_document_chunks_chunk_text_trgm', 'document_chunks', ['chunk_text'], unique=False, postgresql_ops={'chunk_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('document_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_column('classes', 'course_id')
    # ### end Alembic commands ###
