"""Add only_class_id and is_embedding to documents

Revision ID: 535c26ceef9f
Revises: c69f8f7f5503
Create Date: 2026-04-26 11:54:53.249804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535c26ceef9f'
down_revision: Union[str, None] = 'c69f8f7f5503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('only_class_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('is_embedding', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_documents_only_class_id'), 'documents', ['only_class_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'classes', ['only_class_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_only_class_id'), table_name='documents')
    op.drop_column('documents', 'is_embedding')
    op.drop_column('documents', 'only_class_id')
    # ### end Alembic commands ###
