"""make document model courseid nullable

Revision ID: d0b43e2746d0
Revises: a0f835c4973a
Create Date: 2026-04-30 10:40:49.344139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b43e2746d0'
down_revision: Union[str, None] = 'a0f835c4973a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'course_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'course_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
