"""class location fk to room.name 

Revision ID: 6720ff4a6b78
Revises: 583e1d492cd9
Create Date: 2026-04-29 15:30:24.663385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6720ff4a6b78'
down_revision: Union[str, None] = '583e1d492cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_schedules', sa.Column('location', sa.String(length=50), nullable=True, comment='Room name (FK to rooms.name)'))
    op.alter_column('class_schedules', 'schedule_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Session schedule payload: {day, periods}',
               existing_comment='Weekly schedule: {day: [periods]}',
               existing_nullable=False)
    op.create_index(op.f('ix_class_schedules_location'), 'class_schedules', ['location'], unique=False)
    op.create_foreign_key(None, 'class_schedules', 'rooms', ['location'], ['name'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class_schedules', type_='foreignkey')
    op.drop_index(op.f('ix_class_schedules_location'), table_name='class_schedules')
    op.alter_column('class_schedules', 'schedule_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Weekly schedule: {day: [periods]}',
               existing_comment='Session schedule payload: {day, periods}',
               existing_nullable=False)
    op.drop_column('class_schedules', 'location')
    # ### end Alembic commands ###
