"""remove_location_from_classes

Revision ID: 583e1d492cd9
Revises: f982059dac7f
Create Date: 2026-04-28 09:33:28.366758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583e1d492cd9'
down_revision: Union[str, None] = 'f982059dac7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
